# Generated by Django 5.0.6 on 2024-06-27 07:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('vaccination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccination',
            name='slot',
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='updated_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='campaign.slot'),
            preserve_default=False,
        ),
    ]
