# Generated by Django 5.0.6 on 2024-06-27 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
        ('vaccination', '0002_remove_vaccination_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccination',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaign.campaign'),
        ),
    ]
