# Generated by Django 5.0.6 on 2024-06-05 12:37

import user.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
